function n(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}}function p(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):{next:n(a)}}function q(){this.l=!1;this.i=null;this.F=void 0;this.h=1;this.C=this.K=0;this.j=null}function r(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}q.prototype.m=function(a){this.F=a};q.prototype.o=function(a){this.j={L:a,T:!0};this.h=this.K||this.C};
q.prototype["return"]=function(a){this.j={"return":a};this.h=this.C};function t(a){this.g=new q;this.X=a}t.prototype.m=function(a){r(this.g);if(this.g.i)return u(this,this.g.i.next,a,this.g.m);this.g.m(a);return x(this)};function y(a,d){r(a.g);var h=a.g.i;if(h)return u(a,"return"in h?h["return"]:function(k){return{value:k,done:!0}},d,a.g["return"]);a.g["return"](d);return x(a)}t.prototype.o=function(a){r(this.g);if(this.g.i)return u(this,this.g.i["throw"],a,this.g.m);this.g.o(a);return x(this)};
function u(a,d,h,k){try{var l=d.call(a.g.i,h);if(!(l instanceof Object))throw new TypeError("Iterator result "+l+" is not an object");if(!l.done)return a.g.l=!1,l;var f=l.value}catch(g){return a.g.i=null,a.g.o(g),x(a)}a.g.i=null;k.call(a.g,f);return x(a)}function x(a){for(;a.g.h;)try{var d=a.X(a.g);if(d)return a.g.l=!1,{value:d.value,done:!1}}catch(h){a.g.F=void 0,a.g.o(h)}a.g.l=!1;if(a.g.j){d=a.g.j;a.g.j=null;if(d.T)throw d.L;return{value:d["return"],done:!0}}return{value:void 0,done:!0}}
function z(a){this.next=function(d){return a.m(d)};this["throw"]=function(d){return a.o(d)};this["return"]=function(d){return y(a,d)};this[Symbol.iterator]=function(){return this}}function A(a){function d(k){return a.next(k)}function h(k){return a["throw"](k)}return new Promise(function(k,l){function f(g){g.done?k(g.value):Promise.resolve(g.value).then(d,h).then(f,l)}f(a.next())})}
$(document).ready(function(){function a(b,c){client.isConnected()&&(message=new Paho.B.H(c),message.v=b,message.Y=!1,client.send(message))}function d(b){return new Promise(function(c){return setTimeout(c,b)})}function h(b){lastMidi=b;var c="HTML Piano In"==input.Ba?!0:!1;if(b.U()){b.O();b.M();b.P();msg=mqttClientID+":"+b[0]+","+b[1]+","+b[2];a(v,msg);if(!playMeFromServer){var e=output;e.connected()&&e.send(b)}c||l(pianoIn,b)}else if(program=b.Fa())output.Ka(0,b[1]),sendProgramChangeEvents&&(msg=mqttClientID+
":"+b[0]+","+b[1],a(B,msg))}function k(){rttSendTime=Date.now();a(w,mqttClientID+":"+rttMeasured)}function l(b,c){var e=c.O();c.M();var m=c.P();c=new JZZ.s(c);c.Ea()?b.noteOn(0,e,m):c.Da()&&b.noteOff(0,e,m)}var f=p(window.location.href.split("#")),g=f.next().value;f=f.next().value;"undefined"===typeof f&&(f=randomName(),g=g+"#"+f,window.history.replaceState(null,null,"#"+f));$("#sessions").D('Session name: <a href="'+g+'">'+f+"</a>");$("#content").D("Play online with your friends :)");$("h1").Ga("click",
function(){var b;return A(new z(new t(function(c){1==c.h&&(note=21);if(5!=c.h){if(!(108>=note)){c.h=0;return}b=JZZ.s.noteOn(0,note,127);h(b);var e=d(20);c.h=5;return{value:e}}b=JZZ.s.noteOff(0,note,127);h(b);note+=3;c.h=2})))});JZZ();JZZ.Ma.ua.register("Web Audio");pianoIn=JZZ.input.G({u:"pianoIn_space",aa:18,J:10,$:100,I:70,from:"A1",Z:"C7",V:function(){this.R().A({backgroundColor:"#ffe"},{});this.N().A({},{backgroundColor:"#0c9"})}});var C=JZZ.input.G({u:"pianoOut_space",aa:18,J:10,$:100,I:70,from:"A1",
Z:"C7",V:function(){this.R().A({backgroundColor:"#ffe"},{});this.N().A({},{backgroundColor:"#09f"})}});JZZ.input.ba({2:"C#5",3:"D#5",5:"F#5",6:"G#5",7:"A#5",9:"C#6",0:"D#6","+":"F#6",Q:"C5",xa:"D5",E:"E5",pa:"F5",ta:"G5",za:"A5",va:"B5",ia:"C6",na:"D6",oa:"E6","[":"F6","]":"G6",qa:"C#4",fa:"D#4",ga:"F#4",ha:"G#4",ja:"A#4",ka:"C#5",":":"D#5",Aa:"C4",ya:"D4",da:"E4",wa:"F4",ca:"G4",ma:"A4",la:"B4","<":"C5",">":"D5","?":"E5"}).connect(pianoIn);JZZ.Ca("HTML Piano In",pianoIn);input=JZZ.S.ra({u:"sel_in"});
output=JZZ.S.sa({u:"sel_out"});input.connect(h);g="mididerp/sessions/"+f;f=g+"/clients";var v=g+"/noteEvents",w=g+"/rtt",B=g+"/pcnEvents";client=new Paho.B.ea("fandangoc.dmz6.net",8081,mqttClientID);lwt=new Paho.B.H("");lwt.v=f+"/"+mqttClientID;lwt.Y=!0;client.Ha=function(b){0!==b.errorCode&&console.log(new Date+" MQTT onConnectionLost: "+b.errorMessage)};client.Ia=function(b){if(b.v==v){var c=p(b.W.split(":")),e=c.next().value;c=c.next().value.split(",").map(Number);c=new JZZ.s(c);!c.U()||e==mqttClientID&&
1!=playMeFromServer||(e=output,e.connected()&&e.send(c),l(C,c))}else if(b.v==w){var m=p(b.W.split(":"));b=m.next().value;m=m.next().value;b==mqttClientID&&(rttReceived=Date.now(),rttMeasured=rttReceived-rttSendTime);"undefined"===typeof participants[b]&&(participants[b]={});participants[b].rtt=m+" ms";participants[b].lastUpdate=Date.now();for(e in participants)5E3<Date.now()-participants[e].lastUpdate?delete participants[e]:1500<Date.now()-participants[e].lastUpdate&&(participants[e].rtt="stale");
$("#participants").D("Participants:<br>");"undefined"!==typeof participants[mqttClientID]&&$("#participants").append(mqttClientID+" (me) - "+participants[mqttClientID].rtt+"<br>");for(c in participants)c!=mqttClientID&&$("#participants").append(c+" - "+participants[c].rtt+"<br>")}};client.connect({Na:!0,La:!1,timeout:3,Ja:function(){console.log(new Date+" MQTT onConnect");client.subscribe(v);client.subscribe(w);rttTimer=setInterval(k,500)}})});