let vsi_instrumenti = `
<option value="acoustic_grand_piano">acoustic grand piano</option>
<option value="bright_acoustic_piano">bright acoustic piano</option>
<option value="electric_grand_piano">electric grand piano</option>
<option value="honkytonk_piano">honkytonk piano</option>
<option value="electric_piano_1">electric piano 1</option>
<option value="electric_piano_2">electric piano 2</option>
<option value="harpsichord">harpsichord</option>
<option value="clavinet">clavinet</option>
<option value="celesta">celesta</option>
<option value="glockenspiel">glockenspiel</option>
<option value="music_box">music box</option>
<option value="vibraphone">vibraphone</option>
<option value="marimba">marimba</option>
<option value="xylophone">xylophone</option>
<option value="tubular_bells">tubular bells</option>
<option value="dulcimer">dulcimer</option>
<option value="drawbar_organ">drawbar organ</option>
<option value="percussive_organ">percussive organ</option>
<option value="rock_organ">rock organ</option>
<option value="church_organ">church organ</option>
<option value="reed_organ">reed organ</option>
<option value="accordion">accordion</option>
<option value="harmonica">harmonica</option>
<option value="tango_accordion">tango accordion</option>
<option value="acoustic_guitar_nylon">acoustic guitar nylon</option>
<option value="acoustic_guitar_steel">acoustic guitar steel</option>
<option value="electric_guitar_jazz">electric guitar jazz</option>
<option value="electric_guitar_clean">electric guitar clean</option>
<option value="electric_guitar_muted">electric guitar muted</option>
<option value="overdriven_guitar">overdriven guitar</option>
<option value="distortion_guitar">distortion guitar</option>
<option value="guitar_harmonics">guitar harmonics</option>
<option value="acoustic_bass">acoustic bass</option>
<option value="electric_bass_finger">electric bass finger</option>
<option value="electric_bass_pick">electric_bass_pick</option>
<option value="fretless_bass">fretless_bass</option>
<option value="slap_bass_1">slap_bass_1</option>
<option value="slap_bass_2">slap_bass_2</option>
<option value="synth_bass_1">synth_bass_1</option>
<option value="synth_bass_2">synth_bass_2</option>
<option value="violin">violin</option>
<option value="viola">viola</option>
<option value="cello">cello</option>
<option value="contrabass">contrabass</option>
<option value="tremolo_strings">tremolo_strings</option>
<option value="pizzicato_strings">pizzicato_strings</option>
<option value="orchestral_harp">orchestral_harp</option>
<option value="timpani">timpani</option>
<option value="string_ensemble_1">string_ensemble_1</option>
<option value="string_ensemble_2">string_ensemble_2</option>
<option value="synth_strings_1">synth_strings_1</option>
<option value="synth_strings_2">synth_strings_2</option>
<option value="choir_aahs">choir_aahs</option>
<option value="voice_oohs">voice_oohs</option>
<option value="synth_choir">synth_choir</option>
<option value="orchestra_hit">orchestra_hit</option>
<option value="trumpet">trumpet</option>
<option value="trombone">trombone</option>
<option value="tuba">tuba</option>
<option value="muted_trumpet">muted_trumpet</option>
<option value="french_horn">french_horn</option>
<option value="brass_section">brass_section</option>
<option value="synth_brass_1">synth_brass_1</option>
<option value="synth_brass_2">synth_brass_2</option>
<option value="soprano_sax">soprano_sax</option>
<option value="alto_sax">alto_sax</option>
<option value="tenor_sax">tenor_sax</option>
<option value="baritone_sax">baritone_sax</option>
<option value="oboe">oboe</option>
<option value="english_horn">english_horn</option>
<option value="bassoon">bassoon</option>
<option value="clarinet">clarinet</option>
<option value="piccolo">piccolo</option>
<option value="flute">flute</option>
<option value="recorder">recorder</option>
<option value="pan_flute">pan_flute</option>
<option value="blown_bottle">blown_bottle</option>
<option value="shakuhachi">shakuhachi</option>
<option value="whistle">whistle</option>
<option value="ocarina">ocarina</option>
<option value="lead_1_square">lead_1_square</option>
<option value="lead_2_sawtooth">lead_2_sawtooth</option>
<option value="lead_3_calliope">lead_3_calliope</option>
<option value="lead_4_chiff">lead_4_chiff</option>
<option value="lead_5_charang">lead_5_charang</option>
<option value="lead_6_voice">lead_6_voice</option>
<option value="lead_7_fifths">lead_7_fifths</option>
<option value="lead_8_bass__lead">lead_8_bass__lead</option>
<option value="pad_1_new_age">pad_1_new_age</option>
<option value="pad_2_warm">pad_2_warm</option>
<option value="pad_3_polysynth">pad_3_polysynth</option>
<option value="pad_4_choir">pad_4_choir</option>
<option value="pad_5_bowed">pad_5_bowed</option>
<option value="pad_6_metallic">pad_6_metallic</option>
<option value="pad_7_halo">pad_7_halo</option>
<option value="pad_8_sweep">pad_8_sweep</option>
<option value="fx_1_rain">fx_1_rain</option>
<option value="fx_2_soundtrack">fx_2_soundtrack</option>
<option value="fx_3_crystal">fx_3_crystal</option>
<option value="fx_4_atmosphere">fx_4_atmosphere</option>
<option value="fx_5_brightness">fx_5_brightness</option>
<option value="fx_6_goblins">fx_6_goblins</option>
<option value="fx_7_echoes">fx_7_echoes</option>
<option value="fx_8_scifi">fx_8_scifi</option>
<option value="sitar">sitar</option>
<option value="banjo">banjo</option>
<option value="shamisen">shamisen</option>
<option value="koto">koto</option>
<option value="kalimba">kalimba</option>
<option value="bagpipe">bagpipe</option>
<option value="fiddle">fiddle</option>
<option value="shanai">shanai</option>
<option value="tinkle_bell">tinkle_bell</option>
<option value="agogo">agogo</option>
<option value="steel_drums">steel_drums</option>
<option value="woodblock">woodblock</option>
<option value="taiko_drum">taiko_drum</option>
<option value="melodic_tom">melodic_tom</option>
<option value="synth_drum">synth_drum</option>
<option value="reverse_cymbal">reverse_cymbal</option>
<option value="guitar_fret_noise">guitar_fret_noise</option>
<option value="breath_noise">breath_noise</option>
<option value="seashore">seashore</option>
<option value="bird_tweet">bird_tweet</option>
<option value="telephone_ring">telephone_ring</option>
<option value="helicopter">helicopter</option>
<option value="applause">applause</option>
<option value="gunshot">gunshot</option>
`;
$('#select_instruments').append(vsi_instrumenti);